export const SPEAKERS = [
  {
    name: "Prof. Merouane Debbah",
    slug: "prof-merouane-debbah",
    title: "Researcher. President",
    affiliation: "National Scientific Council of AI in Algeria",
    avatar: "public/speakers/1.png",
    bio: "Prof. Debbah is a leading figure in artificial intelligence and telecommunications, with over 20 years of academic and industry experience.",
    topic: "AI in National Development Strategies",
    email: "merouane.debbah@example.com",
    linkedin: "https://www.linkedin.com/in/merouanedebbah",
    twitter: "https://twitter.com/debbah_ai",
    country: "Algeria",
    phone: "+213 123 456 789",
    website: "https://merouanedebbah.ai",
    social: {
      github: "https://github.com/merouanedebbah",
      facebook: "https://facebook.com/merouanedebbah",
    },
    talks: [
      { title: "AI in Government Policies", time: "10:00 AM", room: "A1" },
      { title: "Future of Telecommunications", time: "2:00 PM", room: "B2" },
    ],
    awards: ["Best Researcher 2021", "AI Leadership Award 2019"],
    languages: ["English", "French", "Arabic"],
  },
  {
    name: "Mrs. Rana Fares",
    slug: "mrs-rana-fares",
    title: "Head of Rise Solution Advisory",
    affiliation: "EMEA",
    avatar: "public/speakers/2.png",
    bio: "Rana has been instrumental in driving digital transformation projects across Europe, Middle East, and Africa.",
    topic: "Scaling Businesses with Cloud Solutions",
    email: "rana.fares@example.com",
    linkedin: "https://www.linkedin.com/in/ranafares",
    twitter: "https://twitter.com/rana_fares",
    country: "UAE",
    phone: "+971 50 123 4567",
    website: "https://ranafares.com",
    social: {
      github: "https://github.com/ranafares",
      facebook: "https://facebook.com/ranafares",
    },
    talks: [
      { title: "Cloud Transformation", time: "11:00 AM", room: "C1" },
      { title: "Scaling Startups", time: "3:00 PM", room: "D1" },
    ],
    awards: ["Top 50 Women in Tech 2022"],
    languages: ["English", "French", "Arabic"],
  },
  {
    name: "Mr. Raouf Chebri",
    slug: "mr-raouf-chebri",
    title: "Senior Developer Advocate",
    affiliation: "Neon Geneva, Switzerland",
    avatar: "public/speakers/3.png",
    bio: "Raouf is passionate about empowering developers through open-source projects and advocacy programs.",
    topic: "Modern Database Development",
    email: "raouf.chebri@example.com",
    linkedin: "https://www.linkedin.com/in/raoufchebri",
    twitter: "https://twitter.com/raouf_dev",
    country: "Switzerland",
    phone: "+41 22 123 4567",
    website: "https://raouf.dev",
    social: {
      github: "https://github.com/raoufchebri",
      facebook: "https://facebook.com/raoufchebri",
    },
    talks: [
      { title: "GraphQL vs REST", time: "9:30 AM", room: "E1" },
      { title: "Modern Database Patterns", time: "1:30 PM", room: "F2" },
    ],
    awards: ["Developer Advocate of the Year 2020"],
    languages: ["English", "French"],
  },
  {
    name: "Dr. Sabrina Azzi",
    slug: "dr-sabrina-azzi",
    title: "Assistant Professor",
    affiliation: "University of the West of Scotland (UK)",
    avatar: "public/speakers/4.png",
    bio: "Sabrina’s research focuses on human-computer interaction and the intersection of AI and education.",
    topic: "AI in Higher Education",
    email: "sabrina.azzi@example.com",
    linkedin: "https://www.linkedin.com/in/sabrinaazzi",
    twitter: "https://twitter.com/sabrina_ai",
    country: "United Kingdom",
    phone: "+44 20 1234 5678",
    website: "https://sabrinaazzi.com",
    social: {
      github: "https://github.com/sabrinaazzi",
      facebook: "https://facebook.com/sabrinaazzi",
    },
    talks: [
      { title: "AI-Powered Learning", time: "10:30 AM", room: "G1" },
      { title: "HCI in Education", time: "2:30 PM", room: "H2" },
    ],
    awards: ["Best Young Researcher 2021"],
    languages: ["English", "French"],
  },
  {
    name: "Prof. Rahim Kacimi",
    slug: "prof-rahim-kacimi",
    title: "Associate Professor",
    affiliation: "IRIT",
    avatar: "public/speakers/5.png",
    bio: "Rahim specializes in computer vision and robotics, with numerous published papers in leading journals.",
    topic: "Advancements in Computer Vision",
    email: "rahim.kacimi@example.com",
    linkedin: "https://www.linkedin.com/in/rahimkacimi",
    twitter: "https://twitter.com/rahim_cv",
    country: "France",
    phone: "+33 1 23 45 67 89",
    website: "https://rahimkacimi.fr",
    social: {
      github: "https://github.com/rahimkacimi",
      facebook: "https://facebook.com/rahimkacimi",
    },
    talks: [
      { title: "Computer Vision Trends", time: "11:15 AM", room: "I1" },
      { title: "Robotics in Industry", time: "3:15 PM", room: "J2" },
    ],
    awards: ["Computer Vision Award 2020"],
    languages: ["English", "French"],
  },
  {
    name: "Dr. Houda Chihi",
    slug: "dr-houda-chihi",
    title: "Senior researcher",
    affiliation: "InnovCOM Lab of SupCOM Tunisia",
    avatar: "public/speakers/6.png",
    bio: "Houda’s research is centered around wireless communication and IoT, with a strong focus on smart cities.",
    topic: "IoT and the Future of Smart Cities",
    email: "houda.chihi@example.com",
    linkedin: "https://www.linkedin.com/in/houdachihi",
    twitter: "https://twitter.com/houda_iot",
    country: "Tunisia",
    phone: "+216 71 123 456",
    website: "https://houdachihi.tn",
    social: {
      github: "https://github.com/houdachihi",
      facebook: "https://facebook.com/houdachihi",
    },
    talks: [
      { title: "IoT for Smart Cities", time: "9:45 AM", room: "K1" },
      { title: "Wireless Communication Advances", time: "1:45 PM", room: "L2" },
    ],
    awards: ["IoT Innovator Award 2019"],
    languages: ["English", "French", "Arabic"],
  },
  {
    name: "Mr. Mohamed Magdy",
    slug: "mr-mohamed-magdy",
    title: "Senior Sales Engineer",
    affiliation: "NOZOMI NETWORKS, San Francisco USA",
    avatar: "public/speakers/7.png",
    bio: "Mohamed is an expert in cybersecurity and industrial network security, working with global enterprises.",
    topic: "Securing Industrial Networks",
    email: "mohamed.magdy@example.com",
    linkedin: "https://www.linkedin.com/in/mohamedmagdy",
    twitter: "https://twitter.com/magdy_cyber",
    country: "USA",
    phone: "+1 415 123 4567",
    website: "https://mohamedmagdy.com",
    social: {
      github: "https://github.com/mohamedmagdy",
      facebook: "https://facebook.com/mohamedmagdy",
    },
    talks: [
      { title: "Industrial Network Security", time: "10:15 AM", room: "M1" },
      { title: "Cybersecurity Best Practices", time: "2:15 PM", room: "N2" },
    ],
    awards: ["Top Security Engineer 2021"],
    languages: ["English", "Arabic"],
  },
  {
    name: "Prof. Samir Otmane",
    slug: "prof-samir-otmane",
    title: "Professeur des Universités en Informatique",
    affiliation: "Université Evry Paris-Saclay, France",
    avatar: "public/speakers/8.png",
    bio: "Samir is a pioneer in augmented reality and virtual environments, with decades of teaching and research experience.",
    topic: "Augmented Reality for Education and Training",
    email: "samir.otmane@example.com",
    linkedin: "https://www.linkedin.com/in/samirotmane",
    twitter: "https://twitter.com/samir_ar",
    country: "France",
    phone: "+33 6 12 34 56 78",
    website: "https://samirotmane.fr",
    social: {
      github: "https://github.com/samirotmane",
      facebook: "https://facebook.com/samirotmane",
    },
    talks: [
      { title: "AR in Education", time: "11:30 AM", room: "O1" },
      { title: "Virtual Environments", time: "3:30 PM", room: "P2" },
    ],
    awards: ["AR Innovation Award 2020"],
    languages: ["English", "French"],
  },
];

export const SPONSORS = [
  "public/sponsors/a-venture.webp",
  "public/sponsors/bdl.webp",
  "public/sponsors/bea.webp",
  "public/sponsors/djezzy.webp",
  "public/sponsors/saa.webp",
  "public/sponsors/aba.webp",
  "public/sponsors/bank-agrc.svg",
  "public/sponsors/cnep.png",
  "public/sponsors/gaan.png",
  "public/sponsors/gie.webp",
  "public/sponsors/h24.png",
  "public/sponsors/natixis.webp",
  "public/sponsors/nesda.png",
  "public/sponsors/noubal.jpg",
  "public/sponsors/satim.webp",
  "public/sponsors/ugca.png",
  "public/sponsors/zr.png",
];
