export interface Stand {
  id: string;
  title: string;
  description: string;
  isReserved: boolean;
  reservedBy: string;
  size: string;
}

export const stands: Stand[] = [
  {
    id: "e-3",
    title: "Stand - 3",
    description: "A spacious area perfect for product demonstrations.",
    isReserved: true,
    reservedBy: "TechCorp",
    size: "4M",
  },
  {
    id: "p-3",
    title: "Startup - 3",
    description: "An ideal spot for networking and client meetings.",
    isReserved: false,
    reservedBy: "",
    size: "3M",
  },
  {
    id: "p-1",
    title: "Startup - 1",
    description: "A prime location with high foot traffic.",
    isReserved: false,
    reservedBy: "",
    size: "3M",
  },
  {
    id: "p-2",
    title: "Startup - 2",
    description: "A versatile space suitable for various exhibition needs.",
    isReserved: true,
    reservedBy: "InnovateCo",
    size: "3M",
  },
  {
    id: "p-8",
    title: "Startup - 8",
    description: "A corner stand with excellent visibility.",
    isReserved: false,
    reservedBy: "",
    size: "3M",
  },
  {
    id: "p-7",
    title: "Startup - 7",
    description: "An intimate space for focused presentations.",
    isReserved: true,
    reservedBy: "FutureTech",
    size: "3M",
  },
  {
    id: "p-6",
    title: "Startup - 6",
    description: "A modern setup ideal for tech demonstrations.",
    isReserved: false,
    reservedBy: "",
    size: "3M",
  },
  {
    id: "p-5",
    title: "Startup - 5",
    description: "A cozy spot perfect for one-on-one interactions.",
    isReserved: true,
    reservedBy: "GreenStart",
    size: "3M",
  },
  {
    id: "p-4",
    title: "Startup - 4",
    description: "An open layout suitable for interactive displays.",
    isReserved: false,
    reservedBy: "",
    size: "3M",
  },
  {
    id: "e-20",
    title: "Stand - 20",
    description: "A large area ideal for complex product showcases.",
    isReserved: true,
    reservedBy: "MegaCorp",
    size: "6M",
  },
  {
    id: "e-10",
    title: "Stand - 10",
    description: "A central location with high visibility.",
    isReserved: false,
    reservedBy: "",
    size: "5M",
  },
  {
    id: "e-11",
    title: "Stand - 11",
    description: "An expansive space for comprehensive brand experiences.",
    isReserved: true,
    reservedBy: "GlobalTech",
    size: "5M",
  },
  {
    id: "e-4",
    title: "Stand - 4",
    description: "A flexible space adaptable to various presentation styles.",
    isReserved: false,
    reservedBy: "",
    size: "4M",
  },
  {
    id: "e-5",
    title: "Stand - 5",
    description: "A strategically placed stand for maximum foot traffic.",
    isReserved: true,
    reservedBy: "InnovateNow",
    size: "4M",
  },
  {
    id: "e-12",
    title: "Stand - 12",
    description: "An open concept space for interactive demonstrations.",
    isReserved: false,
    reservedBy: "",
    size: "5M",
  },
  {
    id: "e-13",
    title: "Stand - 13",
    description: "A prime spot for launching new products.",
    isReserved: true,
    reservedBy: "FutureCorp",
    size: "5M",
  },
  {
    id: "e-14",
    title: "Stand - 14",
    description: "A versatile area suitable for multi-product displays.",
    isReserved: false,
    reservedBy: "",
    size: "5M",
  },
  {
    id: "e-15",
    title: "Stand - 15",
    description: "An ideal location for brand storytelling and engagement.",
    isReserved: true,
    reservedBy: "TechGiants",
    size: "5M",
  },
  {
    id: "e-9",
    title: "Stand - 9",
    description: "A compact yet efficient space for focused presentations.",
    isReserved: false,
    reservedBy: "",
    size: "4M",
  },
  {
    id: "e-7",
    title: "Stand - 7",
    description: "A well-positioned stand for maximum brand exposure.",
    isReserved: true,
    reservedBy: "SmartSolutions",
    size: "4M",
  },
  {
    id: "e-21",
    title: "Stand - 21",
    description: "An expansive area perfect for large-scale demonstrations.",
    isReserved: false,
    reservedBy: "",
    size: "6M",
  },
  {
    id: "e-22",
    title: "Stand - 22",
    description: "A premium location ideal for industry leaders.",
    isReserved: true,
    reservedBy: "TechLeaders",
    size: "6M",
  },
  {
    id: "e-23",
    title: "Stand - 23",
    description: "A spacious setup for comprehensive product lines.",
    isReserved: false,
    reservedBy: "",
    size: "6M",
  },
  {
    id: "e-6",
    title: "Stand - 6",
    description: "A dynamic space for interactive customer engagements.",
    isReserved: true,
    reservedBy: "InnovateTech",
    size: "4M",
  },
  {
    id: "e-8",
    title: "Stand - 8",
    description: "An accessible location with high visibility.",
    isReserved: false,
    reservedBy: "",
    size: "4M",
  },
  {
    id: "e-24",
    title: "Stand - 24",
    description: "A premier spot for showcasing flagship products.",
    isReserved: true,
    reservedBy: "TechPioneers",
    size: "6M",
  },
  {
    id: "p-9",
    title: "Startup - 9",
    description: "An innovative space for emerging tech startups.",
    isReserved: false,
    reservedBy: "",
    size: "3M",
  },
];
